### PR TITLE
[APPENG-1662] ⬆️ heroku-cli-util

### PR DESCRIPTION
**Pull request by amyrlam**
https://jira.corp.fastly.com/browse/APPENG-1662

### CODE REVIEW

**Comment by amyrlam** [comment]
hey @andriantoniades, pinging you based on the commit history. Should I bump this to 1.0.4 https://github.com/fastly/heroku-fastly/blob/master/package.json#L3 and then publish to npm?

**Comment by andriantoniades** [comment]
Hey @amyrlam , yes please, and thank you!

**Comment by amyrlam** [comment]
Merging, will bump version again after https://github.com/thisandagain/fastly/pull/42 is merged.

**Comment by amyrlam** [comment]
published 1.0.4

**Pull request merged**
